### ISSUE TITLE
Is treerite::Predictor not thread-safe?

### ISSUE THREAD

**Issue by getumen** [dovahcrow/treerite#3]
Hi!

I want to use treerite::Predictor in multiple theads.
However, treerite::Predictor does not implement Sync.
When I added Sync to treerite::Predictor, the followin error occured.
```
error[E0277]: `*mut c_void` cannot be shared between threads safely
```
Is this error a false positive? Or, is treerite::Predictor really thread unsafe?

I have no idea how to check whether treelite bindings is thread safe or not.
I think adding `Sync` to treerite::Predictor makes this library more outstanding if treelite bindings is thread safe.

**Comment by dovahcrow** [comment]
I remember it was not thread-safe at the time I wrote the code. https://github.com/dmlc/treelite/issues/66
Not sure if they changed that in the latest release.

**Comment by dovahcrow** [comment]
One way to circle around this is to have a dedicated thread for the predictor and take prediction requests from other threads using a channel.

**Comment by getumen** [comment]
Thanks!

> One way to circle around this is to have a dedicated thread for the predictor and take prediction requests from other threads using a channel.

Thanks, again!
This must work well for me!
